### ISSUE TITLE
Clarify which specific hash algorithm `HashOp::Keccak` refers to

### ISSUE THREAD

**Issue by larry0x** [cosmos/ics23#211]
It's unclear whether it refers to Keccak-256, -512, or other variants.

There is no Go or TypeScript implementation of this HashOp. The Rust implementation uses Sha3-512, which is distinct from either  Keccak-256 or -512. None of the implementations has a test case for this.

Would appreciate if this confusion is addressed.

**Comment by crodriguezvega** [comment]
Thank you for opening this issue, @larry0x. This is a very good catch.

May I ask if you're planning to use a variant of Keccak for your use case then?

We should try to find if anybody is using the current `HashOp_Keccak` enum value. If nobody is, then I guess we could:

- Update the name of the enum value to be more explicit of what variant it is used.
- Update the Rust code to use the correct hash operation instead of SHA3-512.
- Optionally add also support in Go and TS code.

But the first two changes are API breaking, so we need to be careful and figure out if we can make those without disruption.

Also I would like to hear @romac's thoughts on this.

**Comment by romac** [comment]
These changes are fine by me, since we do not use Keccak in Hermes, nor in ibc-rs as far as I can tell. Let me page @Farhad-Shabani just to be sure, and to also run these changes by him.

**Comment by Farhad-Shabani** [comment]
> nor in ibc-rs as far as I can tell.

That's right. I also reached out to a potential user, and they are not using the Keccak variant as well. So we should be all set.
